
# Get the data and manifests from lhotse:
# https://github.com/lhotse-speech/lhotse/blob/master/lhotse/recipes/ami.py
# https://lhotse.readthedocs.io/en/latest/api.html#lhotse.cut.MultiCut.trim_to_supervision_groups

- name: ami-train-utterance-group
  # Relative to examples/tagspeech; use an absolute path if stored elsewhere.
  manifest: AMI_manifests/ami-sdm_train_multiASR.jsonl.gz
  hours: 65
  lang: en




